apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: usman10p/ecs-node-app:latest  # Update with your specific tag if needed
          ports:
            - containerPort: 3000  # Adjust if your app uses a different port
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Adjust if your app uses a different port
  type: LoadBalancer

