name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # or any other branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install AWS Elastic Beanstalk CLI (EB CLI)
      - name: Install AWS EB CLI
        run: |
          pip install --upgrade pip
          pip install awsebcli

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Initialize Elastic Beanstalk project
      - name: Initialize EB environment
        run: |
          eb init ${{ secrets.EB_APP_NAME }} --platform "Node.js" --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.EB_ENV_NAME }}

      # Deploy the application
      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy --staged

